//
//  AccessLectureKit.h
//  AccessLecture
//
//  Created by Michael on 1/26/15.
//  Copyright (c) 2015 RIT . All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface AccessLectureKit : NSObject

// Colors
+ (UIColor*)accessBlue;
+ (UIColor*)brushDefault;

// Drawing Methods
+ (void)drawBackButtonWithFrame: (CGRect)frame;
+ (void)drawCreateButtonWithFrame: (CGRect)frame;
+ (void)drawSearchButtonWithFrame: (CGRect)frame;
+ (void)drawBrushButtonWithFrame: (CGRect)frame brushColor: (UIColor*)brushColor;
+ (void)drawSaveButtonWithFrame: (CGRect)frame;
+ (void)drawCheckButtonWithFrame: (CGRect)frame;

// Generated Images
+ (UIImage*)imageOfBackButtonWithFrame: (CGRect)frame;

@end



@interface UIColor (PaintCodeAdditions)

- (UIColor*)blendedColorWithFraction: (CGFloat)fraction ofColor: (UIColor*)color;

@end
